-- 코드를 입력하세요
SELECT  p.PRODUCT_CODE,
        p.PRICE * sum(os.SALES_AMOUNT) as SALES
FROM PRODUCT as p JOIN OFFLINE_SALE as os 
ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES desc, p.PRODUCT_CODE asc;

# SELECT * FROM OFFLINE_SALE;
# SELECT * FROM PRODUCT;